### ISSUE TITLE
Latest update no working

### ISSUE THREAD

**Issue by dharmeshbhana** [wernerhp/ha.integration.load_shedding#99]
Hi

The latest update breaks the integration.

Any ideas? Do I have to uninstall and reinstall?
Need new API ?

Lose all my automations?

**Comment by manieschutte** [comment]
Morning

I have the same problem. Showing a migration error. Nothing in logs showing anything.

**Comment by debug7878** [comment]
Hi

Same problem I've uninstalled and reinstalled the app now I'm unable to reach provider when I search for my location, I think the server is down.

**Comment by fspringhorn-gmail** [comment]
Not sure if I should log a different 'Issue' for the same problem, but I'm also experiencing this after update to v1.5. 

Running HA Core on Raspberry Pi 4. 
Only log details I could find so far: 

> Logger: homeassistant.config_entries
> Source: config_entries.py:983
> First occurred: 8:51:44 AM (1 occurrences)
> Last logged: 8:51:44 AM
> 
> Error migrating entry Load Shedding for load_shedding
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 983, in async_migrate
>     result = await component.async_migrate_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/load_shedding/__init__.py", line 168, in async_migrate_entry
>     config_entry.version = 5
>     ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 468, in __setattr__
>     raise AttributeError(
>         f"{key} cannot be changed directly, use async_update_entry instead"
>     )
> AttributeError: version cannot be changed directly, use async_update_entry instead

**Comment by carlkite** [comment]
> Not sure if I should log a different 'Issue' for the same problem, but I'm also experiencing this after update to v1.5.
> 
> Running HA Core on Raspberry Pi 4. Only log details I could find so far:
> 
> > Logger: homeassistant.config_entries
> > Source: config_entries.py:983
> > First occurred: 8:51:44 AM (1 occurrences)
> > Last logged: 8:51:44 AM
> > Error migrating entry Load Shedding for load_shedding
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/config_entries.py", line 983, in async_migrate
> > result = await component.async_migrate_entry(hass, self)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/config/custom_components/load_shedding/**init**.py", line 168, in async_migrate_entry
> > config_entry.version = 5
> > ^^^^^^^^^^^^^^^^^^^^
> > File "/usr/src/homeassistant/homeassistant/config_entries.py", line 468, in **setattr**
> > raise AttributeError(
> > f"{key} cannot be changed directly, use async_update_entry instead"
> > )
> > AttributeError: version cannot be changed directly, use async_update_entry instead

I am also seeing the same in my logs after upgrading to version 1.5.0

**Comment by J37za** [comment]
Can't use my API key, that I previously used - "Invalid API Key / Token".

**Comment by wernerhp** [comment]
> Can't use my API key, that I previously used - "Invalid API Key / Token".

Please reach out to [Eskom Se Push](https://eskomsepush.gumroad.com/l/api) for issues relating to API Keys / Tokens.

**Comment by wernerhp** [comment]
Everyone else, from which version did you upgrade?
Please see the [release notes](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.5.0)

**Comment by wernerhp** [comment]
I'll take a look at the issue with the migration tonight.  So maybe there's an update tomorrow that doesn't require a reinstall, but a reinstall should sort you out.

**Comment by johanndurandsa** [comment]
Hi Werner. I have reinstalled and still it tells me cannot find provider "Unable to reach Provider. See Logs for details."

**Comment by dharmeshbhana** [comment]
I reverted to previous version and it works fine

**Comment by wernerhp** [comment]
> Hi Werner. I have reinstalled and still it tells me cannot find provider "Unable to reach Provider. See Logs for details."

Which version did you reinstall?  Did you reboot after uninstalling and reinstalling?

Did you "See Logs for details"?  Please search logs for `load_shedding` and post the logs.

**Comment by dharmeshbhana** [comment]
I just used my previous days backup and restore home assistant. The only change was the update for load shedding. So I left it there and didn't update with latest

**Comment by johanndurandsa** [comment]
I have Uninstalled Rebooted Reinstalled, Rebooted and still not working. There is nothing in the Logs. I have also gone back to Last year Version 1.4 and also 1.3 and the Same Issue. I can also revert back to previouse Snapshot and see if this will work

**Comment by johanndurandsa** [comment]
Still Same issue Even revert back to previous snapshot - "Unable to reach Provider. See Logs for details." No Logs in Log File

**Comment by wernerhp** [comment]
I fixed the migration.  Please give [v1.5.1-beta.1](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.5.1-beta.1) a try.
If all goes well I'll release it.

**Comment by wernerhp** [comment]
> Still Same issue Even revert back to previous snapshot - "Unable to reach Provider. See Logs for details." No Logs in Log File

@johanndurandsa please install [v1.5.1-beta.1-debug](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.5.1-beta.1-debug) and let me know if there's anything in the Logs.

**Comment by 949BFN** [comment]
Re-downloading Version 1.5.1 beta via HACS auto-resolved the issue for me. Thanks Werner.

**Comment by johanndurandsa** [comment]
Nope still not working. I have removed old version, rebooted, installed v1.5.1-beta.1, rebooted, created new API Key. Add new API Key then it ask me for my area and then getting this error -  "Unable to reach Provider. See Logs for details.". In the Logs there is still nothing for Load_Shedding

**Comment by johanndurandsa** [comment]
What is the posibility that my IP is been blocked for to many API Try requests?

**Comment by bcameron21** [comment]
I also experienced this error with the 1.5 update. I also re-downloaded the fixed version [v1.5.1-beta.1-debug](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.5.1-beta.1-debug) over the top of the existing installation, without uninstalling the integration, and it is resolved the issue for me.

**Comment by johanndurandsa** [comment]
I have a valid log

Logger: custom_components.load_shedding
Source: custom_components/load_shedding/__init__.py:321
integration: Load Shedding ([documentation](https://github.com/wernerhp/ha_integration_load_shedding/blob/master/README.md), [issues](https://github.com/wernerhp/ha_integration_load_shedding/issues))
First occurred: 22:13:12 (4 occurrences)
Last logged: 22:16:15

Unable to get area schedule: Free account abuse detected - Limited access 🙀. Please pay if you can. Account will be reset in 24 hours.

**Comment by wernerhp** [comment]
@johanndurandsa a second API key from the same IP will get you blocked as per the ESP T&Cs.

`Unable to initialise SePush API: Unable to get areas from SePush.` seems to pint to an issue with the API or your key's permissions.

@carlkite 
I suggest you reach out to Dan and Herman from EskomSePush and provide them with your API key. They'll be able to check why you don't get areas.

**Comment by debug7878** [comment]
Hi @wernerhp 

Here is my log I'm running V1.5.1

This error originated from a custom integration.

Logger: custom_components.load_shedding.config_flow
Source: custom_components/load_shedding/config_flow.py:172
integration: Load Shedding (documentation, issues)
First occurred: 08:12:26 (1 occurrences)
Last logged: 08:12:26

Unable to initialise SePush API: Unable to get areas from SePush.

**Comment by wernerhp** [comment]
<img width="397" alt="Image" src="https://github.com/user-attachments/assets/2441ec90-3a24-4cca-8efa-fdfb9296c7a9" />

@debug7878 @johanndurandsa @carlkite 
Please join [#eskomsepush](https://zatech.slack.com/archives/C043YCM6BRS/p1738647453048159?thread_ts=1738620400.788749&cid=C043YCM6BRS) on https://zatech.co.za/

**Comment by wernerhp** [comment]
Please try calling the API from the terminal, e.g.
```
curl --location 'https://developer.sepush.co.za/business/2.0/areas_search?text=Balito' \
--header 'token: YOUR-API-KEY'
```

**Comment by fspringhorn-gmail** [comment]
HA picked up new update 1.5.1 - I updated and restarted and integration is working 100%. Thanks Werner.

**Comment by wernerhp** [comment]
@debug7878 

<img width="366" alt="Image" src="https://github.com/user-attachments/assets/442d46f8-0ef4-4873-a1e2-a43b796065dc" />

<img width="557" alt="Image" src="https://github.com/user-attachments/assets/01b367de-e524-4460-a58f-39c7370f16fd" />

https://sepush.co.za/license-agreement

**Comment by wernerhp** [comment]
The guys from ESP also found a sync issue with Gumroad.  It should be fixed shortly.  If you still have issues by the end of the day, please join the ZA Slack channel linked in a previous message and ensure you understand and adhere to their API License Agreement.

**Comment by johanndurandsa** [comment]
I am unable to join this group, do not see a link to create a account

Please join [#eskomsepush](https://zatech.slack.com/archives/C043YCM6BRS/p1738647453048159?thread_ts=1738620400.788749&cid=C043YCM6BRS) on https://zatech.co.za/

Please provide the first and last 6 digits of your API key.

**Comment by wernerhp** [comment]
Unfortuantely, I can't do it for you.  You have to read and follow the instructions on the links provided

**Comment by wernerhp** [comment]
<img width="629" alt="Image" src="https://github.com/user-attachments/assets/d4f69f50-5921-463b-ba38-d3e205b33c3e" />

**Comment by debug7878** [comment]
> Closing this thread as the original issue is resolved.

@wernerhp thanks for the help got it going

**Comment by johanndurandsa** [comment]
Do I add my API Key here to assist?
API C1B93956-********-********-60AF2960
